### ISSUE TITLE
Enlarge image

### ISSUE THREAD

**Issue by BV-OpenSource** [aquamorta/kkengraver#12]
Why can't you enlarge an image beyond its give size?

My machine is not kkmoon but it's a INSMA 3000mW so you can add it to the compatible list of machines.

**Comment by BV-OpenSource** [comment]
I wasn't sure if I needed to tag you @aquamorta in order for you to see this.

**Comment by aquamorta** [comment]
Thanks for the 

Hello! This sofware was not ment to be a replacement for an image processing program and upscaling an image is not as straightforward as downscaling. You get artifacts eg. blurry or pixelated images. If you want a larger image use one of the very good image processing programs such as gimp (http://gimp.org).

**Comment by BV-OpenSource** [comment]
> Thanks for the
> 
> Hello! This sofware was not ment to be a replacement for an image processing program and upscaling an image is not as straightforward as downscaling. You get artifacts eg. blurry or pixelated images. If you want a larger image use one of the very good image processing programs such as gimp (http://gimp.org).

I know that those artifacts can occur but I think that it should be an option for the user that comes with a warning.
